# Generated by Django 5.1.3 on 2024-12-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignIn',
            new_name='SignUp',
        ),
    ]
