# Generated by Django 5.1.3 on 2024-12-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_rename_email_signin_emaill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='emaill',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='passwordd',
            new_name='password',
        ),
    ]
